#Requires -Version 5.1
<#
.SYNOPSIS
  Merges DriverStoreManager module sources into standalone Intune detection and remediation scripts.

.DESCRIPTION
  **Safety tier: 2** (writes generated bundles to dist/intune; no network).

  Concatenates Private and Public sources per bundle-order.json, appends entry templates,
  and emits Detect-DsmDriverStoreCompliance.ps1 and Remediate-DsmDriverStore.ps1.
  Exit 0 on success.

.PARAMETER OutputDirectory
  Output folder for generated scripts. Default: dist/intune under project root.

.PARAMETER AgentSummary
  Write exactly one line to the success stream so agents can use a single
  pwsh -NoProfile -File invocation (no Shell compound with if ($LASTEXITCODE)):
  DSM-BUILD-OK detectBytes=N remediateBytes=M on exit 0;
  DSM-BUILD-FAIL exit=N on failure.

.EXAMPLE
  pwsh -NoProfile -File .\scripts\Build-DsmIntuneScripts.ps1

.EXAMPLE
  pwsh -NoProfile -File .\scripts\Build-DsmIntuneScripts.ps1 -AgentSummary

.EXAMPLE
  powershell.exe -NoProfile -ExecutionPolicy Bypass -File .\scripts\Build-DsmIntuneScripts.ps1

.NOTES
  Rebuild after any Private/ change. Entry templates: scripts/intune/templates/*.Entry.ps1.
  Generated dist/ files are auto-generated — edit src/ and re-run this script.

.LINK
  docs/intune-deployment.md
#>
[CmdletBinding()]
param(
    [string] $OutputDirectory,

    [switch] $AgentSummary
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$projectRoot = Resolve-Path (Join-Path $PSScriptRoot '..')
$manifestPath = Join-Path $PSScriptRoot 'intune\bundle-order.json'

if (-not $OutputDirectory) {
    $OutputDirectory = Join-Path $projectRoot 'dist\intune'
}

if (-not (Test-Path -LiteralPath $manifestPath)) {
    throw "Bundle manifest not found: $manifestPath"
}

$manifest = Get-Content -LiteralPath $manifestPath -Raw -Encoding UTF8 | ConvertFrom-Json
$moduleRoot = Join-Path $projectRoot $manifest.moduleRootRelative

function Get-DsmBundledSource {
    param(
        [string[]] $RelativePaths
    )

    $parts = [System.Collections.Generic.List[string]]::new()

    foreach ($rel in $RelativePaths) {
        $full = Join-Path $moduleRoot ($rel -replace '/', '\')
        if (-not (Test-Path -LiteralPath $full)) {
            throw "Missing source file: $full"
        }

        $content = Get-Content -LiteralPath $full -Raw -Encoding UTF8
        $parts.Add("#region DSM source: $rel`r`n$content`r`n#endregion DSM source: $rel") | Out-Null
    }

    return ($parts -join "`r`n`r`n")
}

function New-DsmStandaloneScript {
    param(
        [string] $ScriptType,
        [string] $EntryTemplatePath,
        [string] $OutputFileName,
        [string] $BundleBody
    )

    $entry = Get-Content -LiteralPath $EntryTemplatePath -Raw -Encoding UTF8
    $generatedAt = Get-Date -Format 'yyyy-MM-dd HH:mm:ss K'
    $psVersion = $PSVersionTable.PSVersion.ToString()

    $header = @"
# <auto-generated>
# Driver Store Manager — Intune $ScriptType script
# Generated: $generatedAt
# Builder host PS: $psVersion
# Do not edit by hand; change src/ and run scripts/Build-DsmIntuneScripts.ps1
# </auto-generated>
#Requires -Version 5.1

Set-StrictMode -Version Latest

"@

    $full = $header + $BundleBody + "`r`n`r`n" + $entry
    $outPath = Join-Path $OutputDirectory $OutputFileName

    if (-not (Test-Path -LiteralPath $OutputDirectory)) {
        New-Item -ItemType Directory -Path $OutputDirectory -Force | Out-Null
    }

    if ($PSVersionTable.PSVersion.Major -ge 6) {
        Set-Content -LiteralPath $outPath -Value $full -Encoding utf8NoBOM
    }
    else {
        Set-Content -LiteralPath $outPath -Value $full -Encoding UTF8
    }

    return $outPath
}

$bundleBody = Get-DsmBundledSource -RelativePaths @($manifest.sources)

$detectPath = New-DsmStandaloneScript -ScriptType 'Detection' `
    -EntryTemplatePath (Join-Path $PSScriptRoot 'intune\templates\Detect-DsmDriverStoreCompliance.Entry.ps1') `
    -OutputFileName 'Detect-DsmDriverStoreCompliance.ps1' `
    -BundleBody $bundleBody

$remediatePath = New-DsmStandaloneScript -ScriptType 'Remediation' `
    -EntryTemplatePath (Join-Path $PSScriptRoot 'intune\templates\Remediate-DsmDriverStore.Entry.ps1') `
    -OutputFileName 'Remediate-DsmDriverStore.ps1' `
    -BundleBody $bundleBody

$detectSize = (Get-Item -LiteralPath $detectPath).Length
$remediateSize = (Get-Item -LiteralPath $remediatePath).Length

[pscustomobject]@{
    DetectionScript   = $detectPath
    RemediationScript = $remediatePath
    DetectionBytes    = $detectSize
    RemediationBytes  = $remediateSize
    SourceFileCount   = @($manifest.sources).Count
} | Format-List

Write-Host 'Upload both scripts to Intune Proactive Remediation (64-bit, run as SYSTEM).' -ForegroundColor Green
Write-Host 'See docs/intune-deployment.md for exit codes and pilot guidance.' -ForegroundColor Cyan

if ($AgentSummary) {
    Write-Output ("DSM-BUILD-OK detectBytes={0} remediateBytes={1} sources={2}" -f `
        $detectSize, $remediateSize, @($manifest.sources).Count)
}
